---
# cluster_name is used to group the nodes in a folder within VirtualBox:
cluster_name: Kubernetes Cluster
runtime:
  name: containerd # or crio
  version: 1.6.22-1 # It will be ignored for crio
# Uncomment to set environment variables for services such as crio and kubelet.
# For example, configure the cluster to pull images via a proxy.
# environment: |
#   HTTP_PROXY=http://my-proxy:8000
#   HTTPS_PROXY=http://my-proxy:8000
#   NO_PROXY=127.0.0.1,localhost,master-node,node01,node02,node03
# All IPs/CIDRs should be private and allowed in /etc/vbox/networks.conf.
network:
  # Worker IPs are simply incremented from the control IP.
  control_ip: 10.0.0.10
  dns_servers:
    - 8.8.8.8
    - 1.1.1.1
  pod_cidr: 172.16.1.0/16
  service_cidr: 172.17.1.0/18
nodes:
  control:
    cpu: 2
    memory: 2048
  workers:
    count: 2
    cpu: 2
    memory: 1536
    
# Mount additional shared folders from the host into each virtual machine.
# Note that the project directory is automatically mounted at /vagrant.
shared_folders:
  - host_path: ./synced_volumes/common
    vm_path: /home/vagrant/common
software:
  box: bento/ubuntu-22.04
  calico: 3.26.1
  # To skip the dashboard installation, set its version to an empty value or comment it out:
  dashboard: 2.7.0
  kubernetes: 1.27.1-00
  os: xUbuntu_22.04
  helm: v3.10.2
  ingress_nginx: 4.7.1
  csi_driver_nfs: v4.5.0